apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: httpd-service
  namespace: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpd-deploy
status:
  loadBalancer: {}
